### ISSUE TITLE
inviteUserByEmail() redirectTo param doesn't properly match Redirect URLs

### ISSUE THREAD

**Issue by user72356** [supabase/supabase-js#700]
`supabase.auth.admin.inviteUserByEmail(email, { redirectTo })` doesn't properly match the setup in the Redirect URLs section of the dashboard. 

Per the doc I added `http://localhost:8888/**` into the Redirect URLs setting and this works when signing up with `supabase.auth.signUp({ email, password, options: { emailRedirectTo: "http://localhost:8888" } })`.

However, the exact same setup behaves differently with `supabase.auth.admin.inviteUserByEmail(email, { redirectTo: "http://localhost:8888" })`. In this case I'm being redirected to the URL present in the Site URL setting, because `http://localhost:8888` is not matched up. Only when I add `http://localhost:8888/` (note the trailing slash), does the redirect work with `inviteUserByEmail()`.

So I have to add both `http://localhost:8888/**` AND `http://localhost:8888/` in the Redirect URLs setting!

**Comment by lifeiscontent** [comment]
@kiwicopple I'm seeing similar issues, I have not set an ENV var for SITE_URL but I've manually specified the overrides for all of the redirectUrls of signUp and resetPasswordForEmail but neither are being directed to the correct redirect URL. do I have to manually override:

```toml
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
```

in my `supabase/config.toml`? This seems counter intuitive since its a top level option and a hasstle when dealing with preview deployments.
