### ISSUE TITLE
ci: add `paths-ignore` to ci GHA

### ISSUE THREAD

**Issue by Ananya2001-an** [supabase/supabase-js#791]
# Chore

## Describe the chore
 
Running tests when making changes to .md files or maybe .ignore files can be a bit unnecessary so I guess adding something like below would be good:

```yaml
on:
  push:
    branches:
      - master
      - next
      - rc
    paths-ignore:
      - *.md
      - .gitignore
```

I would like to work on it if it's approved :)
